### ISSUE TITLE
position_ids-->sample_ids

### ISSUE THREAD

**Issue by chaack1** [NREL/htem-api-examples#20]
I was reading through the notebook examples, particularly notebooks 3 and 4,  and I was running into errors when I address Library.properties().position_ids . Apparently position_ids isn't in the Library properties. I played around with it and found sample_ids is the correct index for the Library properties, and it works the same as position_ids ought to. My guess is at some point the name for position_ids was changed to sample _ids and the notebooks weren't updated to reflect the change. Instances of position_ids should be changed to sample_ids.

**Comment by somerandomsequence** [comment]
@meschw04 - I think some of your work on #19 may address the issues that @chaack1 is having. Can you take a look?

**Comment by meschw04** [comment]
Hello @chaack1 ,
Yes, I was re-running these myself a few days ago and ran into the same issue. The API calls were altered slightly in the most recent update, which created some issues in the repository. Updates have been made to reflect these changes. If problems continue or you feel this was not correctly addressed, feel free to reopen the issue.
Best,
meschw04
